### ISSUE TITLE
dhcp Chef-13

### ISSUE THREAD

**Issue by damacus** [sous-chefs/dhcp#78]

**Comment by shortdudey123** [comment]
```
Deprecated features used!
 method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"]) at 2 locations:
   - /tmp/kitchen/cache/cookbooks/dhcp/attributes/default.rb:39:in `from_file'
   - /tmp/kitchen/cache/cookbooks/dhcp/attributes/default.rb:49:in `from_file'
  See https://docs.chef.io/deprecations_attributes.html for further details.
 Cloning resource attributes for directory[/etc/dhcp/shared_networks.d] from prior resource
Previous directory[/etc/dhcp/shared_networks.d]: /tmp/kitchen/cache/cookbooks/dhcp/recipes/_config.rb:55:in `block in from_file'
Current  directory[/etc/dhcp/shared_networks.d]: /tmp/kitchen/cache/cookbooks/dhcp/providers/shared_network.rb:26:in `block in class_from_file' at 1 location:
   - /tmp/kitchen/cache/cookbooks/dhcp/providers/shared_network.rb:26:in `block in class_from_file'
  See https://docs.chef.io/deprecations_resource_cloning.html for further details.
 Cloning resource attributes for directory[/etc/dhcp/shared_networks.d] from prior resource
Previous directory[/etc/dhcp/shared_networks.d]: /tmp/kitchen/cache/cookbooks/dhcp/providers/shared_network.rb:26:in `block in class_from_file'
Current  directory[/etc/dhcp/shared_networks.d]: /tmp/kitchen/cache/cookbooks/dhcp/providers/shared_network.rb:26:in `block in class_from_file' at 1 location:
   - /tmp/kitchen/cache/cookbooks/dhcp/providers/shared_network.rb:26:in `block in class_from_file'
  See https://docs.chef.io/deprecations_resource_cloning.html for further details.
 Cloning resource attributes for template[/etc/dhcp/shared_networks.d/list.conf] from prior resource
Previous template[/etc/dhcp/shared_networks.d/list.conf]: /tmp/kitchen/cache/cookbooks/dhcp/libraries/helpers.rb:45:in `write_include'
Current  template[/etc/dhcp/shared_networks.d/list.conf]: /tmp/kitchen/cache/cookbooks/dhcp/libraries/helpers.rb:45:in `write_include' at 1 location:
   - /tmp/kitchen/cache/cookbooks/dhcp/libraries/helpers.rb:45:in `write_include'
  See https://docs.chef.io/deprecations_resource_cloning.html for further details.
 Cloning resource attributes for directory[/etc/dhcp/classes.d] from prior resource
Previous directory[/etc/dhcp/classes.d]: /tmp/kitchen/cache/cookbooks/dhcp/recipes/_config.rb:55:in `block in from_file'
Current  directory[/etc/dhcp/classes.d]: /tmp/kitchen/cache/cookbooks/dhcp/providers/class.rb:6:in `block in class_from_file' at 1 location:
   - /tmp/kitchen/cache/cookbooks/dhcp/providers/class.rb:6:in `block in class_from_file'
  See https://docs.chef.io/deprecations_resource_cloning.html for further details.
 Cloning resource attributes for directory[/etc/dhcp/classes.d] from prior resource
Previous directory[/etc/dhcp/classes.d]: /tmp/kitchen/cache/cookbooks/dhcp/providers/class.rb:6:in `block in class_from_file'
Current  directory[/etc/dhcp/classes.d]: /tmp/kitchen/cache/cookbooks/dhcp/providers/class.rb:6:in `block in class_from_file' at 1 location:
   - /tmp/kitchen/cache/cookbooks/dhcp/providers/class.rb:6:in `block in class_from_file'
  See https://docs.chef.io/deprecations_resource_cloning.html for further details.
 Cloning resource attributes for template[/etc/dhcp/classes.d/list.conf] from prior resource
Previous template[/etc/dhcp/classes.d/list.conf]: /tmp/kitchen/cache/cookbooks/dhcp/libraries/helpers.rb:45:in `write_include'
Current  template[/etc/dhcp/classes.d/list.conf]: /tmp/kitchen/cache/cookbooks/dhcp/libraries/helpers.rb:45:in `write_include' at 1 location:
   - /tmp/kitchen/cache/cookbooks/dhcp/libraries/helpers.rb:45:in `write_include'
  See https://docs.chef.io/deprecations_resource_cloning.html for further details.
 Cloning resource attributes for directory[/etc/dhcp/subnets.d/] from prior resource
Previous directory[/etc/dhcp/subnets.d/]: /tmp/kitchen/cache/cookbooks/dhcp/providers/subnet.rb:8:in `block in class_from_file'
Current  directory[/etc/dhcp/subnets.d/]: /tmp/kitchen/cache/cookbooks/dhcp/providers/subnet.rb:8:in `block in class_from_file' at 1 location:
   - /tmp/kitchen/cache/cookbooks/dhcp/providers/subnet.rb:8:in `block in class_from_file'
  See https://docs.chef.io/deprecations_resource_cloning.html for further details.
 Cloning resource attributes for template[/etc/dhcp/subnets.d/list.conf] from prior resource
Previous template[/etc/dhcp/subnets.d/list.conf]: /tmp/kitchen/cache/cookbooks/dhcp/libraries/helpers.rb:45:in `write_include'
Current  template[/etc/dhcp/subnets.d/list.conf]: /tmp/kitchen/cache/cookbooks/dhcp/libraries/helpers.rb:45:in `write_include' at 1 location:
   - /tmp/kitchen/cache/cookbooks/dhcp/libraries/helpers.rb:45:in `write_include'
```

**Comment by shortdudey123** [comment]
@jmccann i almost have chef 13 compat done
https://github.com/sous-chefs/dhcp/pull/81 finishes all the of deprecation warnings.

One thing i have not gotten is the LWRPs must not notify resources outside of them which means the `write_include` method in the helpers needs to be reworked.  Not sure the best way to do that

**Comment by lamont-granquist** [comment]
@shortdudey123 it looks like everything is written Chef-10-style.

https://github.com/sous-chefs/dhcp/blob/master/providers/subnet.rb#L12-L33

you should turn on use_inline_resources in those providers.  then just drop all the updated_by_last_action junk entirely.

see:  https://gist.github.com/lamont-granquist/8cda474d6a31fadd3bb3b47a66b0ae78

if these providers are using non-use-inline-resources in order to send notifications to external resources in recipe context (bubble up) then as of chef 12.9.x that works in poise-like ways:

https://gist.github.com/lamont-granquist/b569d0086d19739ebeb3e8c7ab1d65bc

if you need to drop support for chef versions older than 12.9.x i would highly encourage that rather than continuing to write broken resources (and all the code here is broken and buggy it needs to either construct resources directly with Chef::Resource::Whatever.new or use build_resource or use action :nothing, then needs to force running the resource at compile_time and then needs to pull the updated_by_last_action state off of the sub-resource in order to apply it to the wrapping resource correctly -- pretty certain notifications off of these LWRPs don't work correctly and aren't tested).

**Comment by shortdudey123** [comment]
Thats what i figured i would have to do.  I just just trying to avoid ripping it apart which doesn't look like it will work out the way i thought.

Bubbling up the notifications like the gist you posted seems pretty interesting would appears like thats the right way to go
